from ubuntu:trusty

MAINTAINER Andre Pinto <mrs@tlantic.com>

RUN apt-get update
RUN apt-get install -y ca-certificates

RUN mkdir -p /app/

ADD build.tar.gz /app/

WORKDIR /app

EXPOSE  8000

CMD ./api --consul=$MRS_CONSUL